### ISSUE TITLE
Sketch Crashes after using plugin

### ISSUE THREAD

**Issue by rohapa** [littlebusters/JSON-to-Layers#3]
Sketch 40.1 Crashes on Mac OS 10.12 + 10.11.5

**Comment by rohapa** [comment]
Log 
[crash.log.zip](https://github.com/littlebusters/JSON-to-Layers/files/512504/crash.log.zip)

**Comment by littlebusters** [comment]
Could you show me the JSON file?

**Comment by rohapa** [comment]
[Test_Desktop.json.zip](https://github.com/littlebusters/JSON-to-Layers/files/516380/Test_Desktop.json.zip)

**Comment by littlebusters** [comment]
Sketch can't use bitmap as a mask. Using a rectangle instead of a bitmap.
Import a bitmap manually if necessary.
Thanks!

**Comment by rohapa** [comment]
There is are no masks in the fireworks document.

## 

Robert Paige
roberthpaige@gmail.com

**Comment by littlebusters** [comment]
"resource-24.png" was being used as a mask for "Color Fill 1" (perhaps background).

**Comment by rohapa** [comment]
Thanks. That would explain a lot. Keep up the great work!
